# Generated by Django 4.2.2 on 2023-06-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_product_order_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
