# Generated by Django 4.2.2 on 2023-06-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_remove_user_city_remove_user_zip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='building',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='floor',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
