# Generated by Django 4.2.2 on 2023-06-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_remove_address_address_address_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
