# Generated by Django 4.2.2 on 2023-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_alter_address_apartment_alter_address_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='default_add',
            field=models.BooleanField(default=True),
        ),
    ]
