# Generated by Django 4.2.2 on 2023-06-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_address_default_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='default_add',
            field=models.BooleanField(default=False),
        ),
    ]
