# Generated by Django 4.2.2 on 2023-06-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_alter_address_default_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tools.address'),
            preserve_default=False,
        ),
    ]
