# Generated by Django 4.2.2 on 2023-06-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_alter_wishlist_wished_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wished_item',
            new_name='product',
        ),
    ]
